### ISSUE TITLE
SnapPro with Dayz.Epoch.3d.Editor.Live.Mission.With.Database.Interaction

### ISSUE THREAD

**Issue by matt-d-rat** [raymix/SnapPro#11]
Hey, just wondered whether it is possible to get SnapPro working with [Dayz.Epoch.3d.Editor.Live.Mission.With.Database.Interaction](https://github.com/Sandbird/Dayz.Epoch.3d.Editor.Live.Mission-with-Database)? Would love to test it out inside the editor, but of course the default key bindings do not work inside the editor.

I added additional keys as OR conditions to the dayz_spaceInterrupt.sqf but it still doesn't seem to be registering the key presses. Any ideas?

**Comment by raymix** [comment]
Hey, Matt, actually I got too lazy half way Sandbird's tutorial so never installed it.

Truth is, F key is not "bound" per say, in fact its an event handler that checks if key defined using DIK codes is pressed, if so a global bool is turned true. You could simply make your own little EH to simulate it and add it to your init.sqf (google for keydown)

Fast forward to player_build.sqf file and you will find DZE_F bool inside of it. So basically once EH changes this var, object is detached from player, another bool called helperDetach becomes true, which continues chain and either snaps or drops object.
Simple as that, really.

dayz_spaceinterrupt is a function that is called from player monitor FSM:
https://github.com/vbawol/DayZ-Epoch/blob/bbfd03dbf701f0496b239522a4db10516ceb5dab/SQF/dayz_code/system/player_monitor.fsm#L1089

**Comment by matt-d-rat** [comment]
@raymix Yeah the issue seems to be that findDisplay 46 doesn't work in the editor (as described by Sandbird in this readme), so naturally none of the dayz_spaceInterrupt.sqf keys will work. Any ideas on how I can hack my way around? I just wanted to have a play around with SnapPro outside of a real server.

**Comment by matt-d-rat** [comment]
Ok, @Sandbird I think I have found a really hacky way around it the display 46 issue in Dayz.Epoch.3d.Editor.Live.Mission.With.Database.Interaction. 

If you create a custom dialog on screen, it doesn't even technically have to be visible to the player, it just has to be there, and instead attach the event handler to that:

```
_display = uiNamespace getVariable 'DAYZ_GUI_display';
_display displayAddEventHandler ["KeyDown","_this call dayz_spaceInterrupt"];
```

This allows the key bindings to work in the editor. So things like building (should) now work :-).

Edit: It seems the caveat to this though is that it must be a display that relinquishes the controls on the character so that the mouse can freely move. Only then does it seem the key events fire. Hmmm....

**Comment by matt-d-rat** [comment]
Closing the issue as the problem is not in SnapPro.

**Comment by Sandbird** [comment]
@matt-d-rat thanks for that :) will take a look ....maybe i can figure out a way to allow mouse movement as well
